"""add employees, sessions, background_checks

Revision ID: 1aeac88a2d41
Revises:
Create Date: 2026-08-20 10:33:38.880897

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1aeac88a2d41"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_no", sa.String(length=20), nullable=False),
        sa.Column("login_id", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("address", sa.String(length=200), nullable=True),
        sa.Column("department", sa.String(length=50), nullable=True),
        sa.Column("position", sa.String(length=50), nullable=True),
        sa.Column(
            "role", sa.String(length=10), server_default="EMPLOYEE", nullable=False
        ),
        sa.Column(
            "status", sa.String(length=10), server_default="ACTIVE", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('EMPLOYEE', 'ADMIN')", name="ck_employees_role"),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'RESIGNED')", name="ck_employees_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_no"),
    )
    op.create_index("idx_employees_login_id", "employees", ["login_id"], unique=True)
    op.create_table(
        "background_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("check_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("sent_first_name", sa.String(length=50), nullable=False),
        sa.Column("sent_last_name", sa.String(length=50), nullable=False),
        sa.Column("criminal_record", sa.Boolean(), nullable=True),
        sa.Column("education_verified", sa.Boolean(), nullable=True),
        sa.Column("employment_verified", sa.Boolean(), nullable=True),
        sa.Column("credit_score", sa.String(length=10), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "credit_score IS NULL OR credit_score IN ('excellent', 'good', 'fair', 'poor')",
            name="ck_checks_credit",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'clear', 'flagged')", name="ck_checks_status"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("check_id"),
    )
    op.create_index(
        "idx_checks_employee", "background_checks", ["employee_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sessions_employee", "sessions", ["employee_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_sessions_employee", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("idx_checks_employee", table_name="background_checks")
    op.drop_table("background_checks")
    op.drop_index("idx_employees_login_id", table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
